# Archivo de configuración para el despliegue en Docker

services:
  api:
    build: .
    image: ${PROJECT_NAME}-${VERSION_API}-api:latest
    container_name: ${PROJECT_NAME}-${VERSION_API}-api
    restart: unless-stopped
    ports:
      - "${PORT_API}:${PORT_API}"
    env_file:
      - .env
    command: node dist/main
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - bot-demandas-enlinea
      - default
    
  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME}-${VERSION_API}-redis
    restart: unless-stopped
    environment:
      - TZ=America/Bogota
    command: redis-server --port ${REDIS_PORT:-6379}
    networks:
      - bot-demandas-enlinea

networks:
  bot-demandas-enlinea:
    internal: true
